### ISSUE TITLE
No nearby share toggle in latest update 

### ISSUE THREAD

**Issue by elswerky** [Xposed-Modules-Repo/io.github.chsbuffer.miuihelper#1]
Please return back showing nearby share in control center in the latest update

**Comment by chsbuffer** [comment]
[unlock-cn-gms_MIUI14.zip](https://github.com/Xposed-Modules-Repo/io.github.chsbuffer.miuihelper/files/10301923/unlock-cn-gms_MIUI14.zip)

i made this magisk module for **MIUI 14 CN** (won't work for older versions or other systems). The module info was copied from https://github.com/fei-ke/unlock-cn-gms , but not the same elsewhere.
